export const mdiVanish = 'M16,13V11H21V13H16M14.83,7.76L17.66,4.93L19.07,6.34L16.24,9.17L14.83,7.76M11,16H13V21H11V16M11,3H13V8H11V3M4.93,17.66L7.76,14.83L9.17,16.24L6.34,19.07L4.93,17.66M4.93,6.34L6.34,4.93L9.17,7.76L7.76,9.17L4.93,6.34M8,13H3V11H8V13M19.07,17.66L17.66,19.07L14.83,16.24L16.24,14.83L19.07,17.66Z';
export const mdiAlert = 'M13,14H11V10H13M13,18H11V16H13M1,21H23L12,2L1,21Z';
export const icons = {
  'account': 'M12,4A4,4 0 0,1 16,8A4,4 0 0,1 12,12A4,4 0 0,1 8,8A4,4 0 0,1 12,4M12,14C16.42,14 20,15.79 20,18V20H4V18C4,15.79 7.58,14 12,14Z'
};

export const example = [
  '# Header 1',
  '',
  'Paragraph text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text',
  '',
  '## Header 2',
  '',
  'Paragraph text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text',
  '',
  '### Header 3',
  '',
  'Paragraph text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text',
  '',
  '#### Header 4',
  '',
  'Paragraph text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text',
  '',
  'Test [`link code`](#) example.',
  '',
  `<a href="" class="button">icon:account Button</a>`,
  '',
  '- List 1',
  '- List 2',
  '  - List 1 `code`',
  '  - List 2',
  '- List 3 `inline` code',
  '',
  '> Blockquote',
  '',
  '',
  '> **Warning:** Blockquote',
  '',
  '',
  '> **Note:** Blockquote',
  '',
  '',
  '> **Alert:** Blockquote',
  '',
  '> **Attention:** Blockquote',
  '',
  '> **Success:** Blockquote',
  '',
  '> ',
  '>',
  '',
  '```javascript',
  'function foo() {',
  '    // Code',
  '}',
  '```',
  '```typescript',
  'function foo() {',
  '    // Really long item with overlap. test test test test test test test test test test test test test test test test test test',
  '}',
  '```',
  '```markdown',
  '# Header',
  '',
  'Does markdown in markdown work...',
  '```',
  '',
  '```',
  'Nothing',
  '```',
  '',
  '```yaml',
  'type: object',
  'properties:',
  '  id:',
  '    type: string',
  '    format: uuid',
  '  name:',
  '    type: string',
  '    pattern: /$[a-z0-9-]+^/',
  '    example: user',
  '  complex:',
  '    type: object',
  '    properties:',
  '      id:',
  '        type: string',
  '        format: uuid',
  '```',
  '',
  'Tabs without Label',
  '',
  'tabs',
  'tab Tab Title 1',
  '',
  'Anything...',
  '',
  '/tab',
  'tab icon:foo Tab Title 2',
  '',
  'Another tabs `content`.',
  '',
  '/tab',
  '/tabs',
  '',
  '',
  'Tabs with Label',
  '',
  'tabs Label',
  'tab Tab Title 1',
  '',
  'Anything...',
  '',
  '/tab',
  'tab Tab Title 2',
  '',
  'Another tabs `content`.',
  '',
  '/tab',
  '/tabs',
  '',
  '| Header 1             | Header 2 |',
  '|----------------------|----------|',
  '| Row 1... larger size | Row 1    |',
  '| Row 2                | Row 2    |',
  '| Row 3                | Row 3    |',
  '| Row 4                | Row 4    |',
  '',
  'Done, but `code` blocks would be useful.'
].join('\n');